# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-29 16:15
from __future__ import unicode_literals

import angiakhangproject.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=b'images/albums')),
                ('id_project', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', angiakhangproject.models.VarCharField(max_length=1000000000)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company_member', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('avatar_member', models.ImageField(blank=True, upload_to=b'images/member/')),
                ('description', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('type', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(default=0)),
                ('name_portfolio_posts', angiakhangproject.models.VarCharField(max_length=1000000000)),
            ],
            options={
                'db_table': 'portfolioposts',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_portfolio_project', angiakhangproject.models.VarCharField(max_length=1000000000)),
            ],
            options={
                'db_table': 'portfolioproject',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_posts', models.ImageField(blank=True, upload_to=b'images/post/')),
                ('title', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('content', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('portfolio_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angiakhangproject.PortfolioPosts')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('status_progress', models.BooleanField(default=False)),
                ('description_project', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('avatar_image', models.ImageField(blank=True, upload_to=b'images/project')),
                ('year', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angiakhangproject.Area')),
                ('portfolio_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angiakhangproject.PortfolioProject')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('image', models.ImageField(blank=True, upload_to=b'images/slide/')),
            ],
            options={
                'db_table': 'slide',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('name_user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, upload_to=b'images/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('url', angiakhangproject.models.VarCharField(max_length=1000000000)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
