# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-11 06:32
from __future__ import unicode_literals

import angiakhangproject.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='description_portfolio',
            field=angiakhangproject.models.VarCharField(max_length=1000000000, null=True),
        ),
    ]
