# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
