# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='portfolio_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angiakhangproject.PortfolioPosts'),
        ),
    ]
