# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0002_portfolioproject_description_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_interior',
            field=models.BooleanField(default=False),
        ),
    ]
