# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0002_auto_20180930_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'images/portfolioproject/'),
        ),
    ]
