# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0002_auto_20180928_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='id_area',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_company_member',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='id_portfolio_project',
        ),
    ]
