# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0003_auto_20180928_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_member',
            field=models.ImageField(blank=True, upload_to=b'images/member/'),
        ),
    ]
