# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0003_portfolioproject_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'images/video/'),
        ),
    ]
