# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-28 18:01
from __future__ import unicode_literals

import angiakhangproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0004_auto_20180928_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('image', models.ImageField(blank=True, upload_to=b'images/slide/')),
            ],
            options={
                'db_table': 'slide',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', angiakhangproject.models.VarCharField(max_length=1000000000)),
                ('url', angiakhangproject.models.VarCharField(max_length=1000000000)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
