# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-30 12:25
from __future__ import unicode_literals

import angiakhangproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0004_video_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='position',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='url',
            field=angiakhangproject.models.VarCharField(blank=True, max_length=1000000000),
        ),
    ]
