# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-29 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0005_slide_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioposts',
            name='id_portfolio_posts',
        ),
    ]
