# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0005_auto_20180930_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
