# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-29 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0006_remove_portfolioposts_id_portfolio_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id_posts',
        ),
    ]
