# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0008_auto_20180929_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_project',
        ),
        migrations.AlterField(
            model_name='project',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=b'images/project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_album',
            field=models.ImageField(blank=True, upload_to=b'images/albums'),
        ),
    ]
