# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angiakhangproject', '0009_auto_20180929_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_progress',
            field=models.BooleanField(default=False),
        ),
    ]
